### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by digitalsadhu** [ash-framework/roadmap#33]
How should the user be able to specify headers?

**Comment by digitalsadhu** [comment]
Thinking something like:

``` js
class MyRoute extends Ash.Route {
  model () {
    this.headers.set('Content-Type', 'application/json')

    // could also this.headers.get('Content-Type')
  }
}
```

If headers are not explicitly set then we would do our best to work out content type from the content etc.

Thoughts @pnw?

**Comment by pnw** [comment]
If `this.headers` is the response headers, how do I access the request headers?

**Comment by digitalsadhu** [comment]
Hehe yea. That occurred to me after I wrote that and I've been mulling it
over ever since
